// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "./components/Header";
// import { UserProvider } from "./hooks/auth";
// import { Provider } from "react-redux";
// import { Toaster } from "react-hot-toast";
// import store from "@/redux/store";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
// 	title: "E-commerce",
// 	description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
// 	return (
// 		<html lang="en">
// 			<body className={inter.className}>
// 				<Toaster
// 					position="top-center"
// 					reverseOrder={false}
// 					gutter={8}
// 					toastOptions={{
// 						duration: 5000,
// 						style: {
// 							background: "#deede8",
// 							color: "#092635",
// 							border: "5px solid #1b4242",
// 							borderRadius: "15px",
// 							fontSize: "20px",
// 							padding: "8px 32px",
// 						},
// 					}}
// 				/>
// 				<UserProvider>
// 					<div className="mb-[7rem]">
// 						<Header />
// 					</div>
// 					{children}
// 				</UserProvider>
// 			</body>
// 		</html>
// 	);
// }
